### ISSUE TITLE
Cinnamon UNSTABLE 3.0.7: XScreenSavers still points to the (now deleted) screensavers folder

### ISSUE THREAD

**Issue by feren** [linuxmint/cinnamon-screensaver#135]
Basically, in Cinnamon 3.0.7 DEV, you firstly only have Clock as a screensaver option, and secondly, if you restore the /usr/share/cinnamon-screensaver/screensavers folder with the xscreensavers in it, Cinnamon Screensaver still points to it, what's happening with the XScreenSaver portion of the screensaver?

**Comment by mtwebster** [comment]
It's all there - I'm not sure what the issue is for you.  I did split the two plugin types out into separate and optional packages, so if you're just letting the nightlies update your system, you probably don't have them installed.  Try installing cinnamon-screensaver-x-plugin and cinnamon-screensaver-webkit-plugin.

**Comment by feren** [comment]
The time I posted this issue (I am using the Gwendal PPA), the only option in Screensaver was clock unless you backed up the folder for the xscreensaver plugin of which would list them all again...
