### ISSUE TITLE
[Bug?] Can't see Fingerprint GUI overlay on 3.2's screensaver

### ISSUE THREAD

**Issue by feren** [linuxmint/cinnamon-screensaver#160]
Basically, it still is able to unlock the PC, but you don't actually see the GUI for it saying to swipe the finger, etc on it...

**Comment by clefebvre** [comment]
@mtwebster ^^

**Comment by feren** [comment]
@mtwebster The GUI for it is there, but Screensaver overlaps it, also, I've noticed that it mostly only starts checking for fingerprints once you put in a password, and until you place in a correct fingerprint, it remains stuck for some reason on checking... (I've only checked that happening on a correct password)

**Comment by mtwebster** [comment]
Fixed by 38a626d1a3c64736f0

One note in the commit message - this is now working, but the ui strip along the bottom of the screen just flashes a bit - it's prevented from showing by some security-related code to prevent other windows from jumping on top of the screensaver.

There is some cinnamon-specific code in fingerprint-gui source, which needs to be modified (in the `PamGUI.cpp` file) - it is checking to see if the size of the cinnamon-screensaver is monitor-sized before attempting to fix the visibility issue.  In cinnamon-screensaver 3.2, the 'window' it's looking at here is now GdkScreen-sized, which is the size of the smallest rectangle that fully covers all monitors, so it never matches.

I removed the checks against window size, re-built from source, and the fingerprint gui shows up fine now (although it doesn't follow the unlock dialog if you have multiple monitors, but that's minor.)

As I said, though, the current behavior should not prevent fingerprint authentication.
