### ISSUE TITLE
Theming broken with pygobject >= 3.46.0

### ISSUE THREAD

**Issue by bobby285271** [linuxmint/cinnamon-screensaver#446]
### Distribution

Fedora 39 Beta / NixOS unstable

### Package version

5.8.0 (Fedora), 5.8.1 (NixOS)

### Graphics hardware in use

(Not relevant)

### Frequency

Always

### Bug description

Don't know how to improve the issue title, screenshots can describe this issue better I guess.

pygobject 3.44.1 (using Mint-Y theme):

<img src="https://github.com/linuxmint/cinnamon-screensaver/assets/20080233/0f6d9236-3ed4-447b-91b4-9103b689ee9c" width=50%>

pygobject 3.46.0 (using Mint-Y theme):

```
Oct 22 12:22:33 localhost-live cinnamon-screensaver[3879]: Cinnamon Screensaver support not found in current theme - adding some...
```

(edit: never mind, later I noticed that the above log is also shown up in < 3.46.0, including Mint)

<img src="https://github.com/linuxmint/cinnamon-screensaver/assets/20080233/90eead92-ff6d-4a05-ad33-ebb092ebd201" width=50%>

### Steps to reproduce

- Download Fedora 39 Beta Cinnamon ISO and boot into live session
- (Optional) Go to System settings - Themes - Appearance, change from `Dark` to `Mixed` so you can see the difference easier
- Set a password for the live session
- Lock the screen (this will be how it looks like with pygobject 3.44.1)
- Run `dnf upgrade python3-gobject` as root
- Logout and re-login
- Lock the screen (this will be how it looks like with pygobject 3.46.0)

(This can also be reproduced with a everything-up-to-date-GNOME-45 NixOS)

### Expected behavior

The theming looks exactly like before.

### Additional information

A quick bisect takes me to https://gitlab.gnome.org/GNOME/pygobject/-/merge_requests/231 "Fix incompatibility for CssProvider.load_from_data() (GTK 4.10)", though I did not look at how it affects the screensaver here.

**Comment by mtwebster** [comment]
Hi, can you try a couple of things for me?

These lines: https://github.com/linuxmint/cinnamon-screensaver/blob/master/src/cinnamon-screensaver-main.py#L142-L144


Change from:
```python3
            if fallback_prov.load_from_data(fallback_css.encode()):
                Gtk.StyleContext.add_provider_for_screen (Gdk.Screen.get_default(), fallback_prov, 600)
                Gtk.StyleContext.reset_widgets(Gdk.Screen.get_default())
```
to
```python3
            fallback_prov.load_from_data(fallback_css.encode())
            Gtk.StyleContext.add_provider_for_screen (Gdk.Screen.get_default(), fallback_prov, 600)
            Gtk.StyleContext.reset_widgets(Gdk.Screen.get_default())
```
(remove the conditional)

With their patch, they eliminated any return value from `GtkCssProvider.load_from_data` - this return value has been deprecated for a while in Gtk3 (though it still works I guess - we do the same thing in nemo as we do here), but it's gone in Gtk4, which is why they left it out in this override.

I also suspected the `.encode()` in the first line there, but I think that should be ok even with their change.

**Comment by bobby285271** [comment]
Yes, this works for me
